//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginSystem.AdminPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string License { get; set; }
        public string HWID { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<System.DateTime> LastConnection { get; set; }
        public Nullable<bool> Banned { get; set; }
        public string Project { get; set; }
    }
}
