//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginSystem.AdminPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseClients
    {
        public int Id { get; set; }
        public string License { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<int> IdClient { get; set; }
        public string Project { get; set; }
    }
}
